Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AgroControl.DBContexts;
using AgroControl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AgroControl.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private readonly GospodarstwoContext _context;
        private readonly UserManager<AppUser> _userManager;

        public EventController(GospodarstwoContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int page)
        {
            SetViewBagMessages();

            List<EventModelBase> baseEvents = new List<EventModelBase>();

            List<EventRejestrTransportu> eventsRejestrTransportu = 
                await _context.EventsRejestrTransportu.ToListAsync();
            baseEvents.AddRange(eventsRejestrTransportu.Cast<EventModelBase>().ToList());
            
            List<EventRejestrWejscWyjsc> eventsRejestrWejscWyjsc = 
                await _context.EventsRejestrWejscWyjsc.ToListAsync();
            baseEvents.AddRange(eventsRejestrWejscWyjsc.Cast<EventModelBase>().ToList());

            List<EventSpisZwierzat> eventSpisZwierzat = 
                await _context.EventsSpisZwierzat.ToListAsync();
            baseEvents.AddRange(eventSpisZwierzat.Cast<EventModelBase>().ToList());

            List<EventDezynfekcja> eventDezynfekcja = 
                await _context.EventsDezynfekcja.ToListAsync();
            baseEvents.AddRange(eventDezynfekcja.Cast<EventModelBase>().ToList());

            List<EventPrzegladZabezpieczen> eventPrzegladZabezpieczen = 
                await _context.EventsPrzegladZabezpieczen.ToListAsync();
            baseEvents.AddRange(eventPrzegladZabezpieczen.Cast<EventModelBase>().ToList());

            ViewBag.Pages = Math.Ceiling(baseEvents.Count() / 10d);
            ViewBag.Current = page == 0 ? 1 : page;

            if (page != 0)
            {
                int count = baseEvents.Count();
                int start = ((page * 10) - 10) > count ? 0 : ((page * 10) - 10);
                int amount = ((count - start) / 10d) > 1 ? 10 : count - start;
                return View(baseEvents.OrderByDescending(x => x.CreatedDate).ToList().GetRange(start, amount));
            }

            int max = 10;

            if(baseEvents.Count < 10) {
                max = baseEvents.Count;
            }

            return View(baseEvents.OrderByDescending(x => x.CreatedDate).ToList().GetRange(0, max));
        }

        public IActionResult CreateEventRejestrTransportu()
        {
            return View();
        }
        public async Task<IActionResult> CreateEventRejestrWejscWyjsc(int obiektGospodarczyID)
        {
            EventRejestrWejscWyjsc eventRejestrWejscWyjsc = new EventRejestrWejscWyjsc();
            if(obiektGospodarczyID != 0)
            {
                eventRejestrWejscWyjsc.ObiektGospodarczyID = obiektGospodarczyID;
            }
            int gospodarstwoID = await GetCurrentGospodarstwoID();
            ViewData["ObiektyGospodarcze"] = 
                await _context.ObiektyGospodarcze.Where(x => x.GospodarstwoID == gospodarstwoID).ToListAsync();
            return View(eventRejestrWejscWyjsc);
        }
        public IActionResult CreateEventSpisZwierzat()
        {
            return View(new EventSpisZwierzat());
        }
        public async Task<IActionResult> CreateEventDezynfekcja()
        {
            int gospodarstwoID = await GetCurrentGospodarstwoID();
            ViewData["ObiektyGospodarcze"] =
                await _context.ObiektyGospodarcze.Where(x => x.GospodarstwoID == gospodarstwoID).ToListAsync();
            return View(new EventDezynfekcja());
        }
        public async Task<IActionResult> CreateEventPrzegladZabezpieczen()
        {
            int gospodarstwoID = await GetCurrentGospodarstwoID();
            ViewData["ObiektyGospodarcze"] =
                await _context.ObiektyGospodarcze.Where(x => x.GospodarstwoID == gospodarstwoID).ToListAsync();
            return View(new EventPrzegladZabezpieczen());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEventRejestrTransportu(EventRejestrTransportu eventRejestrTransportu)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await CreateEvent(eventRejestrTransportu);
            SetViewBagMessages();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEventRejestrWejscWyjsc(EventRejestrWejscWyjsc eventRejestrWejscWyjsc)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await CreateEvent(eventRejestrWejscWyjsc);
            SetViewBagMessages();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEventSpisZwierzat(EventSpisZwierzat eventSpisZwierzat)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await CreateEvent(eventSpisZwierzat);
            SetViewBagMessages();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEventDezynfekcja(EventDezynfekcja eventDezynfekcja)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await CreateEvent(eventDezynfekcja);
            SetViewBagMessages();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEventPrzegladZabezpieczen(EventPrzegladZabezpieczen eventPrzegladZabezpieczen)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await CreateEvent(eventPrzegladZabezpieczen);
            SetViewBagMessages();
            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEvent<T>(T newEvent) where T : EventModelBase
        {
            try
            {
                var gospodarstwo = await GetCurrentGospodarstwo();

                newEvent.GospodarstwoID = gospodarstwo.ID;
                newEvent.CreatedDate = DateTime.Now;

                if (newEvent.GetType() == typeof(EventRejestrTransportu))
                {
                    EventRejestrTransportu eventRejestrTransportu = 
                        (EventRejestrTransportu)Convert.ChangeType(newEvent, typeof(EventRejestrTransportu));

                    eventRejestrTransportu.EventType = EventTypes.RejestrTransportu;
                    _context.Add(eventRejestrTransportu);
                }
                else if (newEvent.GetType() == typeof(EventRejestrWejscWyjsc))
                {
                    EventRejestrWejscWyjsc eventRejestrWejscWyjsc = 
                        (EventRejestrWejscWyjsc)Convert.ChangeType(newEvent, typeof(EventRejestrWejscWyjsc));

                    //ObiektGospodarczy og = await _context.ObiektyGospodarcze.
                    //    FirstOrDefaultAsync(x => x.ID == int.Parse(eventRejestrWejscWyjsc.NazwaNumerBudynku));

                    //eventRejestrWejscWyjsc.ObiektGospodarczyID = int.Parse(eventRejestrWejscWyjsc.NazwaNumerBudynku);
                    //eventRejestrWejscWyjsc.NazwaNumerBudynku = og.Nazwa;
                    eventRejestrWejscWyjsc.EventType = EventTypes.RejestrWejscWyjsc;
                    _context.Add(eventRejestrWejscWyjsc);
                }
                else if (newEvent.GetType() == typeof(EventSpisZwierzat))
                {
                    EventSpisZwierzat eventSpisZwierzat =
                        (EventSpisZwierzat)Convert.ChangeType(newEvent, typeof(EventSpisZwierzat));

                    eventSpisZwierzat.EventType = EventTypes.SpisZwierzat;
                    _context.Add(eventSpisZwierzat);
                }
                else if (newEvent.GetType() == typeof(EventDezynfekcja))
                {
                    EventDezynfekcja eventDezynfekcja =
                        (EventDezynfekcja)Convert.ChangeType(newEvent, typeof(EventDezynfekcja));

                    eventDezynfekcja.EventType = EventTypes.Dezynfekcja;
                    _context.Add(eventDezynfekcja);
                }
                else if (newEvent.GetType() == typeof(EventPrzegladZabezpieczen))
                {
                    EventPrzegladZabezpieczen eventPrzegladZabezpieczen =
                        (EventPrzegladZabezpieczen)Convert.ChangeType(newEvent, typeof(EventPrzegladZabezpieczen));

                    eventPrzegladZabezpieczen.EventType = EventTypes.PrzegladZabezpieczen;
                    _context.Add(eventPrzegladZabezpieczen);
                }
                else
                {
                    TempData["Message"] += "Nieznany typ zdarzenia";
                    TempData["MessageType"] = "error";  
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] += ex.Message;
                TempData["MessageType"] = "error";
                return View();
            }

            TempData["Message"] += "Pomyślnie dodano zdarzenie do rejestru!";
            TempData["MessageType"] = "success";
            await _context.SaveChangesAsync();

Controllers/PrintoutController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AgroControl.DBContexts;
using AgroControl.Models;
using AgroControl.Utilities;
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace AgroControl.Controllers
{
    public class PrintoutController : Controller
    {
        private IConverter _converter;
        private GospodarstwoContext _context;

        public PrintoutController(IConverter converter, GospodarstwoContext context)
        {
            _converter = converter;
            _context = context;
        }

        [HttpPost]
        public IActionResult CreatePDF(EventTypes eventType, DateTime from, DateTime to)
        {
            if(from == null)
            {
                from = DateTime.MinValue;
            }
            if(to == DateTime.MinValue)
            {
                to = DateTime.Now;
            }

            PDFGenerator pdfGenerator = new PDFGenerator();

            switch (eventType)
            {
                case EventTypes.Dezynfekcja:
                    pdfGenerator.AddEvents<EventDezynfekcja>(
                        _context.EventsDezynfekcja.Where(x => x.DataZabiegu >= from && x.DataZabiegu <= to).ToList()    
                    );
                    break;
                case EventTypes.RejestrTransportu:
                    pdfGenerator.AddEvents<EventRejestrTransportu>(
                        _context.EventsRejestrTransportu.Where(x => x.DataIGodzinaWjazdu >= from && x.DataIGodzinaWjazdu <= to).ToList()    
                    );
                    break;
                case EventTypes.RejestrWejscWyjsc:
                    pdfGenerator.AddEvents<EventRejestrWejscWyjsc>(
                        _context.EventsRejestrWejscWyjsc.Where(x => x.DataIGodzinaWejścia >= from && x.DataIGodzinaWejścia <= to).ToList()    
                    );
                    break;
                case EventTypes.PrzegladZabezpieczen:
                    pdfGenerator.AddEvents<EventPrzegladZabezpieczen>(
                        _context.EventsPrzegladZabezpieczen.Where(x => x.DataPrzegladu>= from && x.DataPrzegladu <= to).ToList()    
                    );
                    break;
                case EventTypes.SpisZwierzat:
                    pdfGenerator.AddEvents<EventSpisZwierzat>(
                        _context.EventsSpisZwierzat.Where(x => x.DataSpisu>= from && x.DataSpisu <= to).ToList()    
                    );
                    break;
                default:
                    pdfGenerator.AddEvents<EventDezynfekcja>(
                        _context.EventsDezynfekcja.Where(x => x.DataZabiegu >= from && x.DataZabiegu <= to).ToList()  
                    );
                    break;
            }
           
            _converter.Convert(pdfGenerator.GetHtmlToPdfDocument());


            //return GetDownload(pdfGenerator.FilePath, $"File_{DateTime.Now.ToString("ddMMyyyHHmm")}.pdf");
            return GetDownload(pdfGenerator.FilePath, $"File.pdf");
        }


        public IActionResult GetDownload(string link, string fileName)
        {
            var net = new System.Net.WebClient();
            var data = net.DownloadData(link);
            var content = new System.IO.MemoryStream(data);
            var contentType = "APPLICATION/octet-stream";
            return File(content, contentType, fileName);
        }



    }

}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgroControl</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/assets/open-iconic/font/css/open-iconic-bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ac-bg-nav border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">AgroControl</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link ac-link-light" asp-controller="Gospodarstwo" asp-action="Index">Gospodarstwo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link ac-link-light" asp-controller="Event" asp-action="Index">Rejestr zdarzeń</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (ViewBag.MessageType == "error")
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if (ViewBag.MessageType == "success")
        {
            <div class="alert alert-success" role="alert">
                @ViewBag.Message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AgroControl @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/rellax.min.js">
        var rellax = new Rellax('.rellax', {
            speed: -2,
            center: false,
            wrapper: null,
            round: true,
            vertical: true,
            horizontal: false
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_ReportGeneraotrModalPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="modal fade" id="pdfGeneratorModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form asp-controller="Printout" asp-action="CreatePDF">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Generowanie raportu.</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <label for="from">Od</label>
                        <input name="from" type="datetime-local" value="@DateTime.Now" class="form-control" />

                        <label for="to">Do</label>
                        <input name="to" type="datetime-local" value="@DateTime.Now" class="form-control" />

                        <label for="eventType">Od</label>
                        <select name="eventType" class="form-control"
                                asp-items="@Html.GetEnumSelectList<EventTypes>()">
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                    <input type="submit" value="CreatePDF" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>