Models/Gospodarstwo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgroControl.Models
{
    public class Gospodarstwo
    {
        public int ID { get; set; }

        [Required]
        public string Nazwa { get; set; }

        [Required]
        [Display(Name = "Właściciel")]
        public string Wlasciciel { get; set; }

        public int UserID { get; set; }


        public virtual ICollection<ObiektGospodarczy> ObiektyGospodarcze { get; set; }

    }
}

Controllers/GospodarstwoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgroControl.DBContexts;
using AgroControl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace AgroControl.Controllers
{
    [Authorize]
    public class GospodarstwoController : Controller
    {
        private readonly GospodarstwoContext _context;

        public GospodarstwoController(GospodarstwoContext context)
        {
            _context = context;
        }

        // GET: Gospodarstwo
        public async Task<IActionResult> Index()
        {
            int userID = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var gospodarstwo = await _context.Gospodarstwo.FirstOrDefaultAsync(x => x.UserID == userID);


            if (gospodarstwo == null)
            {
                return View();
            }
            else
            {
                SetViewBagMessages();
                return View("Details", gospodarstwo);
            }
        }

        // GET: Gospodarstwo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gospodarstwo gospodarstwo = await _context.Gospodarstwo
                .FirstOrDefaultAsync(m => m.ID == id);

            SetViewBagMessages();
            
            if (gospodarstwo == null)
            {
                return NotFound();
            }

            return View(gospodarstwo);
        }

        // GET: Gospodarstwo/Create
        public async Task<IActionResult> Create()
        {
            using (_context)
            {
                int userID = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var gospodarstwo = await _context.Gospodarstwo.FirstOrDefaultAsync(x => x.UserID == userID);

                if (gospodarstwo != null)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        // POST: Gospodarstwo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nazwa,Wlasciciel")] Gospodarstwo gospodarstwo)
        {
            if (ModelState.IsValid)
            {
                int userID = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                gospodarstwo.UserID = userID;

                _context.Add(gospodarstwo);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gospodarstwo);
        }

        // GET: Gospodarstwo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gospodarstwo = await _context.Gospodarstwo.FindAsync(id);
            if (gospodarstwo == null)
            {
                return NotFound();
            }
            return View(gospodarstwo);
        }

        // POST: Gospodarstwo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nazwa,Wlasciciel")] Gospodarstwo gospodarstwo)
        {
            if (id != gospodarstwo.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gospodarstwo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GospodarstwoExists(gospodarstwo.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gospodarstwo);
        }

        // GET: Gospodarstwo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gospodarstwo = await _context.Gospodarstwo
                .FirstOrDefaultAsync(m => m.ID == id);
            if (gospodarstwo == null)
            {
                return NotFound();
            }

            return View(gospodarstwo);
        }

        // POST: Gospodarstwo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gospodarstwo = await _context.Gospodarstwo.FindAsync(id);
            _context.Gospodarstwo.Remove(gospodarstwo);

            TempData["Message"] = "Obiekt gospodarczy usunięty!";
            TempData["MessageType"] = "success";

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GospodarstwoExists(int id)
        {
            return _context.Gospodarstwo.Any(e => e.ID == id);
        }

        private void SetViewBagMessages()
        {
            ViewBag.Message += TempData["Message"];
            ViewBag.MessageType += TempData["MessageType"];
        }
    }
}

Controllers/ObiektGospodarczyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AgroControl.DBContexts;
using AgroControl.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AgroControl.Controllers
{
    public class ObiektGospodarczyController : Controller
    {
        private readonly GospodarstwoContext _context;

        public ObiektGospodarczyController(GospodarstwoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obiektGospodarczy = await _context.ObiektyGospodarcze
                .FirstOrDefaultAsync(m => m.ID == id);
            if (obiektGospodarczy == null)
            {
                return NotFound();
            }

            return View(obiektGospodarczy);
        }

        // GET: ObiektGospodarczyController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ObiektGospodarczyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nazwa")] ObiektGospodarczy obiektGospodarczy)
        {

            int userID = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var gospodarstwo = await _context.Gospodarstwo.FirstOrDefaultAsync(x => x.UserID == userID);

            obiektGospodarczy.Gospodarstwo = gospodarstwo;
            obiektGospodarczy.GospodarstwoID = gospodarstwo.ID;

            if (ModelState.IsValid)
            {
                _context.Add(obiektGospodarczy);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Gospodarstwo");
        }

        //// GET: ObiektGospodarczyController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var obiektGospodarczy = await _context.ObiektyGospodarcze.FindAsync(id);
            if (obiektGospodarczy == null)
            {
                return NotFound();
            }
            return View(obiektGospodarczy);
        }

        //// POST: ObiektGospodarczyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ObiektGospodarczy obiektGospodarczy)
        {
            try
            {
                _context.Update(obiektGospodarczy);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Gospodarstwo");
            }
            catch
            {
                return View();
            }
        }

        // GET: ObiektGospodarczyController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var obiektGospodarczy = await _context.ObiektyGospodarcze
                .FirstOrDefaultAsync(og => og.ID == id);
            if (obiektGospodarczy == null)
            {
                return NotFound();
            }

            _context.ObiektyGospodarcze.Remove(obiektGospodarczy);
            _context.SaveChanges();

            return RedirectToAction("Index", "Gospodarstwo");
        }
    }
}

ViewComponents/DeleteModalViewComponent.cs
using AgroControl.DBContexts;
using AgroControl.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgroControl.ViewComponents
{
    public class DeleteModalViewComponent : ViewComponent
    {
        private readonly GospodarstwoContext _context;

        public DeleteModalViewComponent(GospodarstwoContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Views/Gospodarstwo/Create.cshtml
@model AgroControl.Models.Gospodarstwo

@{
    ViewData["Title"] = "Create";
}

<h4>Tworzenie nowego gospodarstwa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wlasciciel" class="control-label"></label>
                <input asp-for="Wlasciciel" class="form-control" />
                <span asp-validation-for="Wlasciciel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Stwórz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <input type="button" 
           class="btn btn-secondary" 
           value="Powrót" 
           onclick="location.href='@Url.Action("Index", "Gospodarstwo")'" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Gospodarstwo/Delete.cshtml
@model AgroControl.Models.Gospodarstwo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gospodarstwo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wlasciciel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wlasciciel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <input type="button"
               class="btn btn-secondary"
               value="Powrót"
               onclick="location.href='@Url.Action("Index", "Gospodarstwo")'" />
    </form>
</div>

Views/Gospodarstwo/Details.cshtml
@model AgroControl.Models.Gospodarstwo

@{
    ViewData["Title"] = "Details";
}

<h1>Detale</h1>

<div>
    <div class="container">
        <div class="row justify-content-between">
            <div class="col">
                <h4>Informacje o gospodarstwie</h4>
            </div>
            <div class="pb-3">
                <a asp-action="Edit" asp-route-id="@Model.ID" class="nav-item ac-link-dark font-weight-bolder">
                    <span class="oi oi-cog ac-icon-primary px-2 pb-1"></span>
                    Edycja
                </a>
                <a asp-action="Delete" asp-route-id="@Model.ID" class="nav-item ac-link-dark font-weight-bolder">
                    <span class="oi oi-trash ac-icon-primary px-2 pb-1"></span>
                    Usuń
                </a>
                @*<a asp-controller="Home" asp-action="Index">Powrót do strony głównej</a>*@
            </div>
        </div>
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wlasciciel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wlasciciel)
        </dd>
    </dl>
    <hr />
    <div class="col d-flex flex-row-reverse pb-2">
        <a asp-controller="ObiektGospodarczy" asp-action="Create"
           class="nav-item ac-link-dark font-weight-bolder">
            <span class="oi oi-plus ac-icon-primary align-text-top"></span>
            Dodaj obiekt gospodarczy
        </a>
    </div>
    @if (Model.ObiektyGospodarcze != null)
    {
        <div class="container">
            <div class="row justify-content-center">
                @foreach (var obiektGospodarczy in Model.ObiektyGospodarcze)
                {
                    <div class="card col-11 col-xs-11 col-sm-5 col-lg-3 m-2" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">Obiekt: @obiektGospodarczy.Nazwa</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Obiekt gospodarczy</h6>
                            <p class="card-text">Opcje</p>
                            <div class="row justify-content-between p-1">
                                <a data-toggle="tooltip" data-placement="top" title="Edytuj obiekt" asp-action="Edit" asp-controller="ObiektGospodarczy" asp-route-id="@obiektGospodarczy.ID">
                                    <span class="oi oi-cog ac-icon-primary px-2 pb-1"
                                          data-toggle="tooltip" data-placement="top" title="Edytuj obiekt"/>
                                </a>
                                <a data-toggle="tooltip" data-placement="top" title="Dodaj zdarzenie">
                                    <span class="oi oi-calendar ac-icon-primary px-2 pb-1"
                                          data-toggle="modal" data-target="#eventModal" data-id="@obiektGospodarczy.ID" />
                                </a>
                                <a data-toggle="tooltip" data-placement="top" title="Usuń obiekt">
                                    <span class="oi oi-trash ac-icon-primary px-2 pb-1"
                                          data-toggle="modal" data-target="#deleteModal" data-id="@obiektGospodarczy.ID"
                                          data-action="ObiektGospodarczy/Delete/" />
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
</div>
<div>
    @await Component.InvokeAsync("DeleteModal", new { })
    <partial name="_ObiektGospodarczyEventsPartial" />
</div>

Views/Gospodarstwo/Edit.cshtml
@model AgroControl.Models.Gospodarstwo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Gospodarstwo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wlasciciel" class="control-label"></label>
                <input asp-for="Wlasciciel" class="form-control" />
                <span asp-validation-for="Wlasciciel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <input type="button"
           class="btn btn-secondary"
           value="Powrót"
           onclick="location.href='@Url.Action("Index", "Gospodarstwo")'" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Gospodarstwo/Index.cshtml
@model IEnumerable<AgroControl.Models.Gospodarstwo>

@{
    ViewData["Title"] = "Index";
}

<h1>Gospodarstwo</h1>

@if (Model == null)
{
<div class="d-flex justify-content-center p-4 mt-3">
    <input type="button" 
           class="btn btn-success btn-lg" 
           value="Stwórz nowe gospodarstwo" 
           onclick="location.href='@Url.Action("Create", "Gospodarstwo")'" />
</div>
}

Views/Gospodarstwo/_ObiektGospodarczyEventsPartial.cshtml
<div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Które zdarzenie chcesz dodać?
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       data-action="Event/CreateEventRejestrWejscWyjsc/">
                        <img src="~/assets/general/farmer2.svg" width="50" />
                        Rejestr wejść/wyjść
                    </a>
                    <a class="list-group-item list-group-item-action"
                       data-action="Event/CreateEventDezynfekcja/">
                        <img src="~/assets/general/tools.svg" width="50" />
                        Dezynfekcja
                    </a>
                    <a class="list-group-item list-group-item-action" 
                       data-action="Event/CreatePrzegladZabezpieczen/">
                        <img src="~/assets/general/farm.svg" width="50" />
                        Przegląd zabezpieczeń
                    </a>
                    <a class="list-group-item list-group-item-action" 
                       data-action="Event/CreateEventSpisZwierzat/">
                        <img src="~/assets/general/pig.svg" width="50" />
                        Spis zwierząt
                    </a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
            </div>
        </div>
    </div>
</div>